# (trimmed from Jekyll default)
# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: The Frankenwallet
description: Air-gapped transaction building & key backup, secured browser wallets, and private workflow for Cardano & other cryptocurrencies.
theme: just-the-docs
url: https://frankenwallet.com
aux_links:
  Source: https://github.com/rphair/frankenwallet

# https://www.reddit.com/r/Jekyll/comments/zunif0/help_please_i_keep_getting_deprecation_warnings/
sass:
  quiet_deps: true
