# (rphair: trimmed from Jekyll default)
# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: The Frankenwallet
description: Air-gapped transaction building & key backup, secured browser wallets, and private workflow for Cardano & other cryptocurrencies.
theme: just-the-docs
url: https://frankenwallet.com
aux_links:
  Source: https://github.com/rphair/frankenwallet

# (rphair: settings from Minima but not sure if significant to site configuration)
# MAYBE # baseurl: /frankenwallet/docs # the subpath of your site, e.g. /blog
# I'M COMMENTING HERE, BUT WASN'T ON LAUNCH # baseurl: "" # the subpath of your site, e.g. /blog

# Might only be used in Jekyll default Minima...?
email: fw@cosd.com
domain: frankenwallet.com
twitter_username: COSDpool
github_username: rphair
