# (trimmed from Jekyll default)
# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: The Frankenwallet
description: Air-gapped transaction building & key backup, secured browser wallets, and private workflow for Cardano & other cryptocurrencies.
theme: just-the-docs
url: https://frankenwallet.com
color_scheme: green
timezone: Etc/UTC
permalink: pretty

# there appears no way to "substitute" strings in YAML so we'll try to collect all commonly used
#   repository-dependent strings here (in case this location is moved)
aux_links:
  Frankenwallet on GitHub: https://github.com/rphair/frankenwallet
# (taking after the deprecated variable names here: https://just-the-docs.com/docs/configuration/#footer-content)
gh_repository: "https://github.com/rphair/frankenwallet"
gh_branch: "main"  # the branch of current content in the repository
gh_source: "docs"  # subdirectory of current content in the repository

# should be added in override /_includes/footer_custom.html if this variable gets too hairy:
# footer_content: "FOO"

# Not thrilled about this UX but we can think about other options:
back_to_top: true
back_to_top_text: "(back to top)"

# CONTENT PLUGINS (should match Gemfile)
plugins:
  - jekyll-target-blank
  - jekyll-sitemap

# https://just-the-docs.com/docs/configuration/#callouts
# (copied from) https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# https://just-the-docs.com/docs/navigation/main/external
nav_external_links:
  - title: CONTRIBUTING
    url: https://github.com/rphair/frankenwallet/blob/main/CONTRIBUTING.md
      #    hide_icon: false # set to true to hide the external link icon - defaults to false
      #    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# OPERATIONAL SETTINGS

# https://www.reddit.com/r/Jekyll/comments/zunif0/help_please_i_keep_getting_deprecation_warnings/
# https://github.com/jekyll/jekyll-sass-converter#configuration-options
sass:
  silence_deprecations:
    - import
    - color-functions
    - global-builtin
