source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`

# we are not using exotic features to unanticipated upgrades should be fine.
# gem "just-the-docs", "0.10.1" # pinned to the current release
gem "just-the-docs"        # always download the latest release

# PLUGINS used in local preview only
# https://github.com/jekyll/jekyll-sass-converter/pull/164
# https://github.com/jekyll/jekyll-sass-converter/releases/tag/v3.1.0
# This isn't in `plugins:` in _config.yml since we actually *want* deprecation warnings *somewhere*
#   (suppressed in config options while the world waits for Jekyll to use SASS `@use`)
#   so we allow them to generate warnings in the *production* build (and ignore locally):
gem "jekyll-sass-converter", ">=3.1.0"

# CONTENT PLUGINS (should match _config.yml)
# https://github.com/keithmifsud/jekyll-target-blank
gem 'jekyll-target-blank'
# https://github.com/jekyll/jekyll-sitemap
gem 'jekyll-sitemap'
