source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

# (rphair) we are not using exotic features to unanticipated upgrades should be fine.
# gem "just-the-docs", "0.10.1" # pinned to the current release
gem "just-the-docs"        # always download the latest release
